### ISSUE TITLE
Adding multiple contest link buttons in the events page

### ISSUE THREAD

**Issue by srilasyakompella** [linustribevnr/turing-hut-website#28]

**Comment by khssupriya** [comment]
Should we just delete that section of buttons? I dont think its adding anything. Just check the existing events and add those links in that markdown itself if they are not already present.

**Comment by khssupriya** [comment]
@2711-bharath what do you say?

**Comment by 2711-bharath** [comment]
@khssupriya we thought that events might be future events also right like buttons will be necessary if it's a contest in hacker rank or something else right

**Comment by khssupriya** [comment]
We can give the link in the markdown only na, even for contests

**Comment by 2711-bharath** [comment]
oh ok then we can remove

**Comment by khssupriya** [comment]
Ha @srilasyakompella you can remove the important links part

**Comment by srilasyakompella** [comment]
Ok i will do it
